# Key features

## Multi dimensional arrays

## Built in array operation

## Simplified but powerful array interactions

# Why Numpy?

## Speed

## Functionality

## Many packages based on numpy

# >>ndarray basics

### Rank1 numpy array

In [1]:
import numpy as np
an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(3,)


In [3]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
an_array[0] = 434  # ndarray are mutable
print(an_array)

[434  33 333]


### Rank2 numpy array

In [5]:
another = np.array([[11, 22, 33],[23, 45, 23]])
print(another)
print(another.shape)
print(another[0, 1], another[1, 2])

[[11 22 33]
 [23 45 23]]
(2, 3)
22 23


In [6]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [7]:
ex2 = np.full((2,2),9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [8]:
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [9]:
ex4 = np.ones((1, 2))
print(ex4)

[[1. 1.]]


In [10]:
print(ex4.shape)

(1, 2)


In [11]:
print(ex4[0, 1])

1.0


In [12]:
ex5 = np.random.random((2, 2))
print(ex5)

[[0.48666788 0.29164363]
 [0.4632824  0.02379546]]


# ndarray Datatypes and operations

### Datatypes

In [34]:
ex1 = np.array([11, 12])
print(ex1.dtype)

int32


In [35]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


In [36]:
ex3 = np.array([11, 12], dtype = np.float64)
print(ex3.dtype)
print(ex3)

float64
[11. 12.]


In [37]:
ex4 = np.array([11.0, 23.3], dtype = np.int64)
print(ex4.dtype)
print(ex4)

int64
[11 23]


### Arithmetic Array Operations:

In [38]:
x = np.array([[111,112],[121,122]], dtype = np.int64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype = np.float64)
print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


In [40]:
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [41]:
print(x - y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [42]:
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [43]:
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [44]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [45]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]
