# >>Array Indexing

In [2]:
import numpy as np
an_array = np.array([[11,12,13,13],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 13]
 [21 22 23 24]
 [31 32 33 34]]


In [3]:
a_slice = an_array[:2, 1:3] #Just a reference to an_array
print(a_slice)

[[12 13]
 [22 23]]


In [4]:
an_array[0, 1] = 19
print(a_slice)

[[19 13]
 [22 23]]


In [6]:
a_slice[0,1] = 20
print(an_array)


[[11 12 13 13]
 [21 22 23 24]
 [31 32 33 34]]


In [8]:
### Create copy of an_array to a_slice

In [9]:
an_array = np.array([[11,12,13,13],[21,22,23,24],[31,32,33,34]])
print(an_array)
print()
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[11 12 13 13]
 [21 22 23 24]
 [31 32 33 34]]

[[12 13]
 [22 23]]


In [10]:
an_array[0, 1] = 19
print(a_slice)

[[12 13]
 [22 23]]


In [11]:
### Use both integer indexing & slice indexing

In [12]:
an_array = np.array([[11,12,13,13],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 13]
 [21 22 23 24]
 [31 32 33 34]]


In [13]:
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [14]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [15]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [16]:
### Array Indexing for changing elements

In [17]:
import numpy as np
an_array = np.array([[11,12,13], [21,22,23,], [31,32,33],[41,42,43]])
print(an_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [ ]:

col_indices = np.array([0, 1, 2, 0])
print(col_indices)
row_indices = np.arange(4)
print(row_indices)

for row,col in zip(row_indices,col_indices):
    print(row,",",col)

print(an_array[row_indices, col_indices])

an_array[row_indices, col_indices] += 1000
print(an_array)
