# ndarray boolean  indexing

In [3]:
import numpy as np
an_array = np.array([[11, 12],[21, 22],[31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [4]:
filter = (an_array>15)
print(filter)

[[False False]
 [ True  True]
 [ True  True]]


In [6]:
print(an_array[filter])

[ 21 122  31 132]


In [7]:
an_array[(an_array>15) & (an_array <30)]

array([21])

In [10]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 412]
 [ 21 422]
 [ 31 432]]
