In [ ]:
# Statistical , Sorting and Set Operation

In [2]:
import numpy as np
arr = 10 * np.random.rand(2,5)
print(arr)

[[1.06850336e-03 6.46549219e+00 9.87891780e+00 4.12852239e+00
  6.04581196e+00]
 [3.59002295e+00 5.48863630e-01 4.29504300e+00 5.69535784e+00
  2.70757936e+00]]


In [3]:
print(arr.mean())

4.3356679639777544


In [4]:
print(arr.mean(axis = 1))

[5.30396257 3.36737336]


In [5]:
print(arr.mean(axis = 0))

[1.79554573 3.50717791 7.0869804  4.91194012 4.37669566]


In [6]:
print(arr.sum())

43.356679639777546


In [7]:
print(arr.sum(axis = 0))

[ 3.59109145  7.01435583 14.17396081  9.82388023  8.75339132]


In [8]:
print(np.median(arr, axis = 0 ))

[1.79554573 3.50717791 7.0869804  4.91194012 4.37669566]


### Sorting

In [9]:
unsorted = np.random.randn(10)
print(unsorted)

[-0.45292664  0.15834003  0.27184923  0.4548045   1.6800007  -0.59517035
  0.18442963 -0.50472884 -0.2003186  -1.04356167]


In [10]:
sorted = np.array(unsorted)

In [11]:
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.04356167 -0.59517035 -0.50472884 -0.45292664 -0.2003186   0.15834003
  0.18442963  0.27184923  0.4548045   1.6800007 ]

[-0.45292664  0.15834003  0.27184923  0.4548045   1.6800007  -0.59517035
  0.18442963 -0.50472884 -0.2003186  -1.04356167]


### Find Unique elements:

In [12]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


### Set Operations with np.array data type:

In [13]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [14]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [15]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [16]:
print(np.setdiff1d(s1,s2))

['desk']


In [17]:
print(np.in1d(s1,s2))

[False  True  True]
