# Broadcasting

In [2]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
add_rows = np.array([1,0,3])
print(add_rows)

[1 0 3]


In [4]:
y =start + add_rows
print(y)

[[1. 0. 3.]
 [1. 0. 3.]
 [1. 0. 3.]
 [1. 0. 3.]]


In [5]:
add_cols = np.array([[0,1,2,3]]).T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [6]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [7]:
add_scaler = np.array([1])
print(add_scaler)

[1]


In [8]:
y = start + add_scaler
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
